# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProfHacks iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProfHacks iOS

  target 'ProfHacks iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProfHacks iOSUITests' do
    # Pods for testing
  end

end
